const express = require("express");
const router = express.Router();
const authOnly = require("../middleware/authOnly");
const AdminOnly = require("../middleware/AdminOnly");
const fileUpload = require("../middleware/file-upload");
const { articles, createArticle } = require("../controllers/blog");
router.use(authOnly);
router.post("/articles", articles);
router.use(AdminOnly);
router.post("/create", fileUpload.single("image"), createArticle);
module.exports = router;
